In [1]:
# Importer les bibliothèques nécessaires au programme

In [2]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les compagnies se présentant aléatoirement à l'entrée du donjon 

## pour simplifier, une compagnie sera représentée par la somme des puissances 
# des aventuriers qui la compose

# aventurier_1	aventurier_2	aventurier_3	puissance
# belette	    belette	        belette	        24
# belette	    belette         chevalier	    27
# chevalier	    chevalier	    belette	        30
# belette	    belette	        elfe	        31
# chevalier	    chevalier	    chevalier	    33
# chevalier   	elfe	        belette	        34
# chevalier  	chevalier	    elfe	        37
# elfe	        elfe	        belette	        38
# elfe	        elfe	        chevalier       41
# elfe	        elfe	        elfe	        45

## shéma du perceptron : 
# puissance de la compagnie ------poids de la compagnie-----neurone------>prediction
# poids de la sorcière (biais) -------------------------------|


In [4]:
compagnie_faible = [24,27,30,31,33]
compagnie_forte = [34,37,38,41,45]

In [5]:
# Définir les étiquettes des données d'entraînement : 
# 0 = envoyer un troll
# 1 = envoyer deux trolls

In [6]:
etiquettes_cat0 = np.zeros_like(compagnie_faible)
etiquettes_cat1 = np.ones_like(compagnie_forte)

In [7]:
# Concaténer les données et les étiquettes 

In [8]:
donnees_entree = np.concatenate([compagnie_faible, compagnie_forte])
print(donnees_entree)
etiquettes = np.concatenate([etiquettes_cat0, etiquettes_cat1])
print(etiquettes)

[24 27 30 31 33 34 37 38 41 45]
[0 0 0 0 0 1 1 1 1 1]


In [9]:
# Mélanger les données 

In [10]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
print(donnees_entree)
etiquettes = etiquettes[indices_melanges]
print(etiquettes)

[24 33 38 30 37 34 31 45 27 41]
[0 0 1 0 1 1 0 1 0 1]


In [11]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(1, input_dim=1, activation='sigmoid'))
## permet de former un modèle avec 1 couche (1 neurone), recevant une seule donnée (input_dim=1)
## la fonction d'activation du modèle est la fonction sigmoide

In [12]:
modele = Sequential()
modele.add(Dense(1, input_dim=1, activation='sigmoid'))

In [13]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [14]:
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
# Entraîner le modèle
## ce sera à vous de rechercher comment fonctionne cette commande

In [16]:
modele.fit(donnees_entree, etiquettes, epochs=200, batch_size=1)

Epoch 1/200


10/10 [==============================] - 1s 3ms/step - loss: 6.5571 - accuracy: 0.5000
Epoch 2/200
10/10 [==============================] - 0s 2ms/step - loss: 6.4450 - accuracy: 0.5000
Epoch 3/200
10/10 [==============================] - 0s 2ms/step - loss: 6.3457 - accuracy: 0.5000
Epoch 4/200
10/10 [==============================] - 0s 2ms/step - loss: 6.2411 - accuracy: 0.5000
Epoch 5/200
10/10 [==============================] - 0s 2ms/step - loss: 6.1251 - accuracy: 0.5000 
Epoch 6/200
10/10 [==============================] - 0s 2ms/step - loss: 6.0455 - accuracy: 0.5000 
Epoch 7/200
10/10 [==============================] - 0s 2ms/step - loss: 5.9167 - accuracy: 0.5000
Epoch 8/200
10/10 [==============================] - 0s 2ms/step - loss: 5.8078 - accuracy: 0.5000
Epoch 9/200
10/10 [==============================] - 0s 5ms/step - loss: 5.7110 - accuracy: 0.5000
Epoch 10/200
10/10 [==============================] - 0s 2ms/step - loss: 5.6145 - accuracy: 0.5000
Epoch

In [17]:
# Évaluer le modèle

In [18]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

1/1 [==============================] - 0s 186ms/step - loss: 0.6415 - accuracy: 0.6000
Perte : 0.6415320634841919, Précision : 0.6000000238418579


In [19]:
# Demander à afficher les prédictions associées à chaque compagnie
# Si la prédiction est > à 0.5, cela signifie que la compagnie est dangereuse

In [20]:
compagnies = [24,27,30,31,33,34,37,38,41,45]
predictions = modele.predict(compagnies)
print("Prédictions:")
print(predictions)

1/1 [==============================] - 0s 119ms/step
Prédictions:
[[0.49713016]
 [0.51545495]
 [0.5337382 ]
 [0.5398149 ]
 [0.55193126]
 [0.55796725]
 [0.575966  ]
 [0.58192354]
 [0.5996467 ]
 [0.62287086]]


In [21]:
# Pouvez-vous en déduire l'équation utilisée dans ce modèle,
# pour déterminer la valeur du "x" qui est transmis à la 
# fonction d'activation sigmoide ? 

In [22]:
# (puissance de la compagnie * poids de la compagnie) + poids de la sorcière
# en fait, c'est la somme de toutes les entrées (y compris le biais) multiplié par leur poids

In [23]:
# Afficher les prédictions, les étiquettes associées et la décision en chaine de caractère

In [24]:
resultat = []
predictions = modele.predict(donnees_entree)
for i in range(10) :
    if predictions[i] < 0.5 :
        resultat.append('1 troll')
    else :
        resultat.append('2 troll')

print(predictions[0:10])
print(etiquettes[0:10])
print(resultat)

1/1 [==============================] - 0s 25ms/step
[[0.49713016]
 [0.55193126]
 [0.58192354]
 [0.5337382 ]
 [0.575966  ]
 [0.55796725]
 [0.5398149 ]
 [0.62287086]
 [0.51545495]
 [0.5996467 ]]
[0 0 1 0 1 1 0 1 0 1]
['1 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll']


In [25]:
# Afficher les poids du modèle

In [26]:
modele.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.02443958]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([-0.5980293], dtype=float32)>]

In [27]:
# Afficher les informations résumées relatives au modèle

In [28]:
modele.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
