In [5]:
# Importer les bibliothèques nécessaires au programme
#!pip install tensorflow

In [6]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les compagnies se présentant aléatoirement à l'entrée du donjon 

## pour simplifier, une compagnie sera représentée par la somme des puissances 
# des aventuriers qui la compose

# aventurier_1	aventurier_2	aventurier_3	puissance
# belette	    belette	        belette	        24
# belette	    belette         chevalier	    27
# chevalier	    chevalier	    belette	        30
# belette	    belette	        elfe	        31
# chevalier	    chevalier	    chevalier	    33
# chevalier   	elfe	        belette	        34
# chevalier  	chevalier	    elfe	        37
# elfe	        elfe	        belette	        38
# elfe	        elfe	        chevalier       41
# elfe	        elfe	        elfe	        45

## shéma du perceptron : 
# puissance de la compagnie ------poids de la compagnie-----neurone------>prediction
# poids de la sorcière (biais) -------------------------------|


In [34]:
compagnie_faible = [24,27,30,31,33]
compagnie_forte = [34,37,38,41,45]

In [35]:
# Définir les étiquettes des données d'entraînement : 
# 0 = envoyer un troll
# 1 = envoyer deux trolls

etiquettes_zeros_like = np.zeros_like(compagnie_faible)
print(etiquettes_zeros_like)
etiquettes_one_like = np.ones_like(compagnie_forte)
print(etiquettes_one_like)
#? indice : zero_like()

[0 0 0 0 0]
[1 1 1 1 1]


In [36]:
# Concaténer les données et les étiquettes
donnees_entree = np.concatenate((compagnie_faible, compagnie_forte), axis=0)
print(donnees_entree)

etiquettes = np.concatenate((etiquettes_zeros_like, etiquettes_one_like), axis=0)
print(etiquettes)

#? indice : np.concatenate()

[24 27 30 31 33 34 37 38 41 45]
[0 0 0 0 0 1 1 1 1 1]


In [37]:
# Mélanger les données 

In [39]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
print(donnees_entree)
etiquettes = etiquettes[indices_melanges]
print(etiquettes)

[38 34 27 33 45 30 41 37 31 24]
[1 1 0 0 1 0 1 1 0 0]


In [40]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(1, input_dim=1, activation='sigmoid'))
## permet de former un modèle avec 1 couche (1 neurone), recevant une seule donnée (input_dim=1)
## la fonction d'activation du modèle est la fonction sigmoide

In [41]:
modele = Sequential()
modele.add(Dense(1, input_dim=1, activation='sigmoid'))

In [42]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [43]:
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [44]:
# Entraîner le modèle
## ce sera à vous de rechercher comment fonctionne cette commande

In [45]:
modele.fit(donnees_entree, etiquettes, epochs=200, batch_size=1)

Epoch 1/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5181 - loss: 11.9945      
Epoch 2/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3241 - loss: 15.5464     
Epoch 3/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.6949 - loss: 7.0012   
Epoch 4/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.4141 - loss: 12.9769  
Epoch 5/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7472 - loss: 5.6007   
Epoch 6/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.4074 - loss: 12.9403   
Epoch 7/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3850 - loss: 13.4978     
Epoch 8/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5812 - loss: 9.2509     
Epoch 9/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3059 - loss: 14.9216     
Epoch 10/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6040 - loss: 8.3052   
Epoch 11/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.5744 - loss: 9.2725   
Ep

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4339 - loss: 0.7492     
Epoch 133/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.4289 - loss: 0.7404   
Epoch 134/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - accuracy: 0.6911 - loss: 0.6631
Epoch 135/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.4418 - loss: 0.7429   
Epoch 136/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - accuracy: 0.5198 - loss: 0.7129
Epoch 137/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.5030 - loss: 0.7218   
Epoch 138/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6828 - loss: 0.6638
Epoch 139/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.5744 - loss: 0.6976
Epoch 140/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.3801 - loss: 0.7582   
Epoch 141/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.4305 - loss: 0.7463   
Epoch 142/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5955 - loss: 0.6927 
Epoch 143/200
10/1

In [30]:
# Évaluer le modèle

In [46]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.7157
Perte : 0.7157341241836548, Précision : 0.5


In [47]:
# Demander à afficher les prédictions associées à chaque compagnie
# Si la prédiction est > à 0.5, cela signifie que la compagnie est dangereuse
print(donnees_entree)
modele.predict(donnees_entree)

[38 34 27 33 45 30 41 37 31 24]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[0.5730154],
       [0.5771098],
       [0.5842494],
       [0.5781318],
       [0.5658263],
       [0.5811937],
       [0.569938 ],
       [0.57404  ],
       [0.5801738],
       [0.5872986]], dtype=float32)

In [ ]:
# Pouvez-vous en déduire l'équation utilisée dans ce modèle,
# pour déterminer la valeur du "x" qui est transmis à la 
# fonction d'activation sigmoide ? 
non
# force compagnie:
#38
# poids:
# -0.00418886
# 0.45334148
# resultat
0.5730154

In [21]:
# Afficher, pour les 10 premières compagnies qui se présentent au donjon :
    # La puissance des compagnies
    # les étiquettes associées (0 ou 1)
    # les prédictions, 
    # et la décision à prendre, en chaine de caractère

In [48]:
predictions = modele.predict(donnees_entree)
resultat = []
for i in range(10) :
    if predictions[i] < 0.5 :
        resultat.append('1 troll')
    else :
        resultat.append('2 troll')

print(predictions[0:10])
print(etiquettes[0:10])
print(resultat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[0.5730154]
 [0.5771098]
 [0.5842494]
 [0.5781318]
 [0.5658263]
 [0.5811937]
 [0.569938 ]
 [0.57404  ]
 [0.5801738]
 [0.5872986]]
[1 1 0 0 1 0 1 1 0 0]
['2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll']


In [23]:
# Afficher les poids du modèle

In [62]:
multiple_poids = modele.weights
for poids in multiple_poids:
    print(poids.value)

# weights = [np.array(weight) for weight in modele.weights]

# # Afficher les poids
# for i, weight_array in enumerate(weights):
#     print(f"Poids {i + 1}:")
#     print(weight_array)

<tf.Variable 'sequential_1/dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.00418886]], dtype=float32)>
<tf.Variable 'sequential_1/dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.45334148], dtype=float32)>


In [25]:
# Afficher les informations résumées relatives au modèle

In [52]:
modele.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8 (36.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6 (28.00 B)