In [112]:
# Importer les bibliothèques nécessaires au programme

In [138]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [139]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les compagnies se présentant aléatoirement à l'entrée du donjon 

## pour simplifier, une compagnie sera représentée par la somme des puissances 
# des aventuriers qui la compose

# aventurier_1	aventurier_2	aventurier_3	puissance
# belette	    belette	        belette	        24
# belette	    belette         chevalier	    27
# chevalier	    chevalier	    belette	        30
# belette	    belette	        elfe	        31
# chevalier	    chevalier	    chevalier	    33
# chevalier   	elfe	        belette	        34
# chevalier  	chevalier	    elfe	        37
# elfe	        elfe	        belette	        38
# elfe	        elfe	        chevalier       41
# elfe	        elfe	        elfe	        45

## shéma du perceptron : 
# puissance de la compagnie ------poids de la compagnie-----neurone------>prediction
# poids de la sorcière (biais) -------------------------------|


In [140]:
import itertools
compagnion_possibilities = [8,11,15]

all_combinaisons = list(itertools.product(compagnion_possibilities, compagnion_possibilities, compagnion_possibilities))
print(toutes_combinaisons)

[(8, 8, 8), (8, 8, 11), (8, 8, 15), (8, 11, 8), (8, 11, 11), (8, 11, 15), (8, 15, 8), (8, 15, 11), (8, 15, 15), (11, 8, 8), (11, 8, 11), (11, 8, 15), (11, 11, 8), (11, 11, 11), (11, 11, 15), (11, 15, 8), (11, 15, 11), (11, 15, 15), (15, 8, 8), (15, 8, 11), (15, 8, 15), (15, 11, 8), (15, 11, 11), (15, 11, 15), (15, 15, 8), (15, 15, 11), (15, 15, 15)]


In [141]:
compagnion_1 = []
compagnion_2 = []
compagnion_3 = []
total_score = []
for combinaison in all_combinaisons:
    compagnion_1.append(combinaison[0])
    compagnion_2.append(combinaison[1])
    compagnion_3.append(combinaison[2])
    total_score.append(combinaison[0]+combinaison[1]+combinaison[2])
    
print(compagnion_1)
print(compagnion_2)
print(compagnion_3)
print(total_score)

# 27 combinaisons

[8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15]
[8, 8, 8, 11, 11, 11, 15, 15, 15, 8, 8, 8, 11, 11, 11, 15, 15, 15, 8, 8, 8, 11, 11, 11, 15, 15, 15]
[8, 11, 15, 8, 11, 15, 8, 11, 15, 8, 11, 15, 8, 11, 15, 8, 11, 15, 8, 11, 15, 8, 11, 15, 8, 11, 15]
[24, 27, 31, 27, 30, 34, 31, 34, 38, 27, 30, 34, 30, 33, 37, 34, 37, 41, 31, 34, 38, 34, 37, 41, 38, 41, 45]


In [142]:
# Creer un plus grand jeu de données pour améliorer l'apprentissage du perceptron

In [143]:
compagnion_1 = compagnion_1 *10
compagnion_2 = compagnion_2 *10
compagnion_3 = compagnion_3 *10
total_score = total_score *10

print(compagnion_1)
print(compagnion_2)
print(compagnion_3)
print(total_score)
print(len(compagnion_1), len(compagnion_2), len(compagnion_3), len(total_score))

[8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 8, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15]
[8, 8, 8,

In [144]:
# Définir les étiquettes des données d'entraînement : 
# 0 = envoyer un troll
# 1 = envoyer deux trolls

In [145]:
etiquettes = []
for score in total_score:
    if score < 34:
        etiquettes.append(0)
    else:
        etiquettes.append(1)

print(etiquettes)

[0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]


In [146]:
# Mélanger les données 

In [147]:
indices_melanges = np.random.permutation(len(etiquettes)).tolist()

compagnion_1 = [compagnion_1[i] for i in indices_melanges]
compagnion_2 = [compagnion_2[i] for i in indices_melanges]
compagnion_3 = [compagnion_3[i] for i in indices_melanges]
total_score = [total_score[i] for i in indices_melanges]
etiquettes = [etiquettes[i] for i in indices_melanges]


In [148]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(1, input_dim=1, activation='sigmoid'))
## permet de former un modèle avec 1 couche (1 neurone), recevant une seule donnée (input_dim=1)
## la fonction d'activation du modèle est la fonction sigmoide

In [149]:
modele = Sequential()
modele.add(Dense(1, input_dim=3, activation='sigmoid'))

In [125]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [126]:
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [127]:
# Entraîner le modèle
## ce sera à vous de rechercher comment fonctionne cette commande

In [136]:
# modele.fit([compagnion_1, compagnion_2, compagnion_3], etiquettes, epochs=400, batch_size=1)

# modele.fit(np.array([compagnion_1, compagnion_2, compagnion_3]), etiquettes, epochs=400, batch_size=1)

modele.fit([np.array(compagnion_1), np.array(compagnion_2), np.array(compagnion_3)], etiquettes, epochs=400, batch_size=1)

# merged_compagnions = np.stack([compagnion_1, compagnion_2, compagnion_3], axis=1)
# modele.fit(merged_compagnions, etiquettes, epochs=400, batch_size=1)

ValueError: Unrecognized data type: x=[array([11, 15, 11, 15,  8,  8, 11, 15,  8,  8, 15,  8,  8, 15, 15, 15, 15,
        8,  8,  8, 15, 15, 11, 15,  8,  8, 11, 15,  8, 15, 15, 11, 15, 15,
        8, 11, 15, 11, 15, 15,  8, 11, 11, 11,  8, 15, 15, 11,  8, 11,  8,
        8, 15,  8, 15, 15, 15, 15, 15, 15, 15, 11, 15, 11, 11,  8,  8, 15,
       15, 11, 15, 11,  8, 11,  8, 15, 11, 11, 15, 15, 11, 15, 11,  8,  8,
       15, 15, 11, 11, 15, 11,  8, 15,  8,  8, 11,  8, 11,  8, 15, 11, 15,
       15, 15, 11, 11, 11,  8,  8, 15,  8, 15,  8,  8,  8, 15, 11,  8, 11,
       15,  8, 15, 15, 11, 15, 15, 11, 15, 15, 11, 15,  8, 11, 15, 11, 11,
       15, 11,  8, 11, 11, 15, 11, 11, 15,  8,  8, 11, 11,  8, 11, 15,  8,
        8, 15, 15,  8,  8, 11,  8, 15, 15, 11, 11, 11,  8,  8, 11,  8, 11,
        8, 15,  8, 15,  8, 15,  8, 11,  8,  8, 15, 11, 11,  8, 15,  8, 11,
       15, 15,  8, 11,  8, 11, 11,  8, 15, 11,  8,  8, 11,  8, 11,  8,  8,
       15, 11,  8, 11,  8, 11, 15, 11, 15, 11, 11,  8,  8, 15, 11, 15, 11,
       15, 11, 15,  8, 11,  8,  8,  8, 11,  8, 11,  8,  8, 11, 11, 15,  8,
       15,  8, 11,  8,  8,  8, 15, 11, 11,  8, 15, 15, 11, 11, 15,  8, 11,
       11,  8, 11,  8,  8, 11, 11,  8, 15, 15, 11,  8, 15, 11, 15]), array([ 8, 15, 11, 11, 15,  8,  8, 15,  8, 15, 11, 11,  8, 11,  8, 15,  8,
        8,  8, 15, 11, 15, 15, 11,  8,  8,  8, 15, 15, 15, 15, 15, 11, 15,
        8, 15, 15, 15,  8,  8, 15,  8, 11,  8,  8,  8, 15, 15, 15, 11, 11,
        8,  8, 15,  8,  8, 11, 15, 11,  8,  8, 15, 15, 11,  8, 11,  8, 11,
        8,  8,  8,  8, 11,  8,  8,  8, 11,  8, 15, 11, 11, 11,  8, 11,  8,
        8,  8, 11, 15, 11, 15, 15, 15, 11,  8, 11, 11, 15,  8,  8, 15,  8,
       11,  8, 15, 15, 15, 15, 15, 11, 11, 11,  8, 15, 11,  8,  8, 11, 15,
       11, 11, 11, 11,  8, 11, 15, 11, 15, 15, 15,  8, 15, 15, 15, 11, 15,
       15, 15, 15, 11,  8, 11,  8,  8, 11, 15, 15, 11, 11,  8,  8, 15, 11,
       11,  8, 15, 11, 11, 11, 11, 15, 11, 15, 11, 11,  8, 11,  8, 15, 15,
       15, 15,  8, 11, 15,  8, 11, 15, 15, 11, 15,  8, 11, 15,  8, 15, 15,
       15, 15,  8,  8,  8, 11,  8, 11,  8,  8, 11, 15, 15, 15, 11,  8,  8,
       11, 15, 15, 15, 15, 11, 15, 11,  8,  8, 11, 11, 11, 15, 11, 15, 15,
       11, 15,  8,  8,  8, 15,  8, 11, 11,  8,  8,  8, 15, 11,  8, 11,  8,
        8, 11,  8, 15, 11,  8, 15, 11, 11, 11,  8,  8, 11, 15, 11, 15, 15,
        8,  8, 15, 15, 11,  8, 11, 11, 11, 11,  8, 11,  8, 11, 11]), array([11, 15,  8, 15, 11, 15, 15, 11, 15, 15, 11,  8,  8,  8,  8, 15, 11,
       11, 15,  8, 11,  8, 15, 15,  8,  8,  8,  8,  8, 15, 11, 11,  8,  8,
        8,  8, 15, 15, 11, 15, 11, 15, 15, 11, 11, 15,  8, 11, 11,  8, 15,
       15, 15, 11,  8,  8, 11, 15, 15, 15, 15, 15,  8,  8, 15, 11, 11,  8,
       15, 15,  8, 11, 15,  8, 11,  8, 11, 15, 11, 11,  8,  8, 11, 15, 15,
        8, 11, 11, 11, 11, 11, 15, 11, 15, 15, 15,  8, 11, 11, 15, 15, 11,
       15, 11, 11,  8, 11, 15,  8, 15,  8,  8, 11, 11, 15,  8, 11, 11,  8,
       11, 15, 11, 15, 11,  8, 15, 15, 11,  8, 15, 15, 15, 11,  8, 15,  8,
       11, 15, 15, 11, 11, 11,  8, 11, 15, 15,  8,  8, 11, 11, 15, 11, 15,
       15, 15,  8, 11, 11,  8, 15,  8, 11, 11, 11, 11,  8,  8,  8, 15,  8,
        8, 15, 15, 15, 15,  8, 11,  8, 15, 11, 11, 15, 15, 15, 11, 11,  8,
       15, 11, 15, 11,  8, 15,  8, 11, 11,  8, 11, 11,  8, 11,  8, 15, 11,
       15, 15,  8, 11,  8, 11, 11, 11, 11, 15, 15,  8,  8,  8, 11, 15, 15,
        8,  8, 15,  8, 11,  8, 11,  8, 15, 11,  8,  8,  8, 11,  8, 15, 15,
       11, 11, 15, 11, 11,  8, 15,  8,  8,  8, 11,  8, 15,  8,  8, 11, 15,
        8,  8, 15,  8,  8,  8, 15, 15,  8, 11, 15,  8,  8,  8,  8])] (of type <class 'list'>)

In [41]:
# Évaluer le modèle

In [42]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - accuracy: 1.0000 - loss: 0.1921
Perte : 0.1845465749502182, Précision : 1.0


In [43]:
# Demander à afficher les prédictions associées à chaque compagnie

In [47]:
compagnies = np.array([24,27,30,31,33,34,37,38,41,45])
predictions = modele.predict(compagnies)
print("Prédictions:")
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Prédictions:
[[0.02007324]
 [0.07037731]
 [0.21862033]
 [0.30195668]
 [0.5083639 ]
 [0.61519104]
 [0.8552479 ]
 [0.9013304 ]
 [0.9712314 ]
 [0.99484277]]


In [48]:
# Afficher les prédictions, les étiquettes associées et la décision en chaine de caractère

In [49]:
resultat = []
for i in range(10) :
    if predictions[i] < 0.5 :
        resultat.append('1 troll')
    else :
        resultat.append('2 troll')

print(predictions[0:10])
print(etiquettes[0:10])
print(resultat)

[[0.02007324]
 [0.07037731]
 [0.21862033]
 [0.30195668]
 [0.5083639 ]
 [0.61519104]
 [0.8552479 ]
 [0.9013304 ]
 [0.9712314 ]
 [0.99484277]]
[0 1 1 0 0 1 0 0 1 0]
['1 troll', '1 troll', '1 troll', '1 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll']


In [50]:
# Afficher les poids du modèle

In [51]:
modele.weights

[<KerasVariable shape=(1, 1), dtype=float32, path=sequential_1/dense_1/kernel>,
 <KerasVariable shape=(1,), dtype=float32, path=sequential_1/dense_1/bias>]

In [52]:
# Afficher les informations résumées relatives au modèle

In [53]:
modele.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8 (36.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6 (28.00 B)