In [1]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Définir les données d'entraînement
compagnie_faible = [[8,8,8],[8,8,11],[11,11,8],[8,8,15],[11,11,11]]
compagnie_forte = [[11,15,8],[11,11,15],[15,15,8],[15,15,11],[15,15,15]]

valeurs_entree_cat0 = []
valeurs_entree_cat1 = []

for i in range(50) :
    # val = random.randint(0,4)
    for val in range(5) :
        valeurs_entree_cat0.append(compagnie_faible[val])
        valeurs_entree_cat1.append(compagnie_forte[val])

#print(len(valeurs_entree_cat0))
#print(len(valeurs_entree_cat1))

# Étiquettes correspondantes (0 pour la catégorie 0, 1 pour la catégorie 1)
etiquettes_cat0 = np.zeros(len(valeurs_entree_cat0), dtype = int)
etiquettes_cat1 = np.ones(len(valeurs_entree_cat1), dtype = int)

# Concaténer les données et les étiquettes
donnees_entree = np.concatenate([valeurs_entree_cat0, valeurs_entree_cat1])
print(donnees_entree)
etiquettes = np.concatenate([etiquettes_cat0, etiquettes_cat1])
print(etiquettes)

# Mélanger les données
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
print(donnees_entree)
etiquettes = etiquettes[indices_melanges]
print(etiquettes)

# Créer le modèle
modele = Sequential()
modele.add(Dense(1, input_dim=3, activation='sigmoid'))

# Compiler le modèle
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entraîner le modèle
modele.fit(donnees_entree, etiquettes, epochs=400, batch_size=1)

# Évaluer le modèle
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

# Prédictions
predictions = modele.predict(donnees_entree)
print("Prédictions:")
print(predictions)


[[ 8  8  8]
 [ 8  8 11]
 [11 11  8]
 ...
 [15 15  8]
 [15 15 11]
 [15 15 15]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1

C:\Users\gaeta\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 574us/step - accuracy: 0.5816 - loss: 0.6042
Epoch 2/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.6256 - loss: 0.5907
Epoch 3/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.6344 - loss: 0.5800
Epoch 4/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step - accuracy: 0.6599 - loss: 0.5515
Epoch 5/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 0.7412 - loss: 0.5335
Epoch 6/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 528us/step - accuracy: 0.7266 - loss: 0.5185
Epoch 7/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.7261 - loss: 0.5353
Epoch 8/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step - accuracy: 0.6861 - loss: 0.5415
Epoch 9/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.6967 - loss: 0.5444
Epoch 10/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.7010 - loss: 0.5513
Epoch 11/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.7163 - loss: 0.5168
Epoch 12/400
500/500 ━━━━━━━━━━

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.9278 - loss: 0.2562
Epoch 133/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 528us/step - accuracy: 0.9420 - loss: 0.2727
Epoch 134/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step - accuracy: 0.9218 - loss: 0.2493
Epoch 135/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.9482 - loss: 0.2767
Epoch 136/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 0.9609 - loss: 0.2513
Epoch 137/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.9405 - loss: 0.2545
Epoch 138/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.9088 - loss: 0.2586
Epoch 139/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - accuracy: 0.9585 - loss: 0.2461
Epoch 140/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step - accuracy: 0.9302 - loss: 0.2447
Epoch 141/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.9503 - loss: 0.2364
Epoch 142/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.9512 - loss: 0.2490
Epoch 143/400

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - accuracy: 1.0000 - loss: 0.1637
Epoch 263/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.9966 - loss: 0.1680
Epoch 264/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 1.0000 - loss: 0.1621
Epoch 265/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 1.0000 - loss: 0.1601
Epoch 266/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 1.0000 - loss: 0.1616
Epoch 267/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 1.0000 - loss: 0.1633
Epoch 268/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9973 - loss: 0.1716
Epoch 269/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 1.0000 - loss: 0.1597
Epoch 270/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step - accuracy: 1.0000 - loss: 0.1598
Epoch 271/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 1.0000 - loss: 0.1630
Epoch 272/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - accuracy: 1.0000 - loss: 0.1547
Epoch 273/400

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 1.0000 - loss: 0.1145
Epoch 393/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 1.0000 - loss: 0.1229
Epoch 394/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - accuracy: 1.0000 - loss: 0.1303
Epoch 395/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 1.0000 - loss: 0.1230
Epoch 396/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 1.0000 - loss: 0.1163
Epoch 397/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 528us/step - accuracy: 1.0000 - loss: 0.1271
Epoch 398/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step - accuracy: 1.0000 - loss: 0.1239
Epoch 399/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step - accuracy: 1.0000 - loss: 0.1251
Epoch 400/400
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 1.0000 - loss: 0.1186
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 1.0000 - loss: 0.1100 
Perte : 0.12032966315746307, Précision : 1.0
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
Prédictions:
[[0.0171592 ]
 [0.10654

In [2]:
resultat = []
for i in range(10) :
    if predictions[i] < 0.5 :
        resultat.append('1 troll')
    else :
        resultat.append('2 troll')

print(predictions[0:9])
print(etiquettes[0:9])
print(resultat)

[[0.0171592 ]
 [0.10654162]
 [0.9900809 ]
 [0.27094942]
 [0.97501385]
 [0.97501385]
 [0.07362859]
 [0.97501385]
 [0.628517  ]]
[0 0 1 0 1 1 0 1 1]
['1 troll', '1 troll', '2 troll', '1 troll', '2 troll', '2 troll', '1 troll', '2 troll', '2 troll', '1 troll']


In [3]:
modele.weights

[<KerasVariable shape=(3, 1), dtype=float32, path=sequential/dense/kernel>,
 <KerasVariable shape=(1,), dtype=float32, path=sequential/dense/bias>]

In [4]:
modele.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14 (60.00 B)

 Trainable params: 4 (16.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 10 (44.00 B)