In [1]:
# Importer les bibliothèques nécessaires au programme

In [2]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les compagnies se présentant aléatoirement à l'entrée du donjon 

## pour simplifier, une compagnie sera représentée par la somme des puissances 
# des aventuriers qui la compose

# aventurier_1	aventurier_2	aventurier_3	puissance
# belette	    belette	        belette	        24
# belette	    belette         chevalier	    27
# chevalier	    chevalier	    belette	        30
# belette	    belette	        elfe	        31
# chevalier	    chevalier	    chevalier	    33
# chevalier   	elfe	        belette	        34
# chevalier  	chevalier	    elfe	        37
# elfe	        elfe	        belette	        38
# elfe	        elfe	        chevalier       41
# elfe	        elfe	        elfe	        45

## shéma du perceptron : 
# puissance de la compagnie ------poids de la compagnie-----neurone------>prediction
# poids de la sorcière (biais) -------------------------------|


In [4]:
compagnie_faible = [24,27,30,31,33]
compagnie_forte = [34,37,38,41,45]

In [5]:
# Définir les étiquettes des données d'entraînement : 
# 0 = envoyer un troll
# 1 = envoyer deux trolls

In [6]:
etiquettes_cat0 = np.zeros_like(compagnie_faible)
etiquettes_cat1 = np.ones_like(compagnie_forte)

In [7]:
# Concaténer les données et les étiquettes 

In [8]:
donnees_entree = np.concatenate([compagnie_faible, compagnie_forte])
print(donnees_entree)
etiquettes = np.concatenate([etiquettes_cat0, etiquettes_cat1])
print(etiquettes)

[24 27 30 31 33 34 37 38 41 45]
[0 0 0 0 0 1 1 1 1 1]


In [9]:
# Mélanger les données 

In [10]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
print(donnees_entree)
etiquettes = etiquettes[indices_melanges]
print(etiquettes)

[27 34 45 31 24 37 30 38 33 41]
[0 1 1 0 0 1 0 1 0 1]


In [11]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(1, input_dim=1, activation='sigmoid'))
## permet de former un modèle avec 1 couche (1 neurone), recevant une seule donnée (input_dim=1)
## la fonction d'activation du modèle est la fonction sigmoide

In [12]:
modele = Sequential()
modele.add(Dense(1, input_dim=1, activation='sigmoid'))

C:\Users\gaeta\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [14]:
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
# Entraîner le modèle
## ce sera à vous de rechercher comment fonctionne cette commande

In [16]:
modele.fit(donnees_entree, etiquettes, epochs=200, batch_size=1)

Epoch 1/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5744 - loss: 16.4895     
Epoch 2/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.4620 - loss: 19.3873   
Epoch 3/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6317 - loss: 12.6980  
Epoch 4/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5030 - loss: 17.5865     
Epoch 5/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6381 - loss: 12.7320  
Epoch 6/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.4293 - loss: 19.5256  
Epoch 7/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.4045 - loss: 20.8897   
Epoch 8/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.5631 - loss: 15.6951  
Epoch 9/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.4045 - loss: 21.7811   
Epoch 10/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6797 - loss: 10.9177    
Epoch 11/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.2399 - loss: 26.5939   
Ep

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.5168 - loss: 0.8194   
Epoch 132/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5683 - loss: 0.7904 
Epoch 133/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5198 - loss: 0.8253 
Epoch 134/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.2747 - loss: 0.7900     
Epoch 135/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.3681 - loss: 0.8245   
Epoch 136/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.2423 - loss: 0.8295     
Epoch 137/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.3049 - loss: 0.7629   
Epoch 138/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.4144 - loss: 0.7341
Epoch 139/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.2127 - loss: 0.7642   
Epoch 140/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.0283 - loss: 0.7688   
Epoch 141/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.2754 - loss: 0.7456
Epoch 142/200
10

In [17]:
# Évaluer le modèle

In [18]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 0.7447
Perte : 0.7447474598884583, Précision : 0.5


In [19]:
# Demander à afficher les prédictions associées à chaque compagnie
# Si la prédiction est > à 0.5, cela signifie que la compagnie est dangereuse

In [21]:
compagnies = [24,27,30,31,33,34,37,38,41,45]
predictions = modele.predict(compagnies)
print("Prédictions:")
print(predictions)

ValueError: Unrecognized data type: x=[24, 27, 30, 31, 33, 34, 37, 38, 41, 45] (of type <class 'list'>)

In [22]:
# Pouvez-vous en déduire l'équation utilisée dans ce modèle,
# pour déterminer la valeur du "x" qui est transmis à la 
# fonction d'activation sigmoide ? 

In [23]:
# (puissance de la compagnie * poids de la compagnie) + poids de la sorcière
# en fait, c'est la somme de toutes les entrées (y compris le biais) multiplié par leur poids

In [24]:
# Afficher les prédictions, les étiquettes associées et la décision en chaine de caractère

In [25]:
resultat = []
predictions = modele.predict(donnees_entree)
for i in range(10) :
    if predictions[i] < 0.5 :
        resultat.append('1 troll')
    else :
        resultat.append('2 troll')

print(predictions[0:10])
print(etiquettes[0:10])
print(resultat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.6035314 ]
 [0.57756925]
 [0.53594625]
 [0.58875734]
 [0.6144909 ]
 [0.56630087]
 [0.592467  ]
 [0.56252897]
 [0.581308  ]
 [0.55117124]]
[0 1 1 0 0 1 0 1 0 1]
['2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll', '2 troll']


In [26]:
# Afficher les poids du modèle

In [27]:
modele.weights

[<KerasVariable shape=(1, 1), dtype=float32, path=sequential/dense/kernel>,
 <KerasVariable shape=(1,), dtype=float32, path=sequential/dense/bias>]

In [28]:
# Afficher les informations résumées relatives au modèle

In [29]:
modele.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8 (36.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6 (28.00 B)