In [1]:
# Importer les bibliothèques nécessaires au programme
#!pip install tensorflow

In [2]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les compagnies se présentant aléatoirement à l'entrée du donjon 

## pour simplifier, une compagnie sera représentée par la somme des puissances 
# des aventuriers qui la compose

# aventurier_1	aventurier_2	aventurier_3	puissance
# belette	    belette	        belette	        24
# belette	    belette         chevalier	    27
# chevalier	    chevalier	    belette	        30
# belette	    belette	        elfe	        31
# chevalier	    chevalier	    chevalier	    33
# chevalier   	elfe	        belette	        34
# chevalier  	chevalier	    elfe	        37
# elfe	        elfe	        belette	        38
# elfe	        elfe	        chevalier       41
# elfe	        elfe	        elfe	        45

## shéma du perceptron : 
# puissance de la compagnie ------poids de la compagnie-----neurone------>prediction
# poids de la sorcière (biais) -------------------------------|


In [4]:
possibility_compagnie_faible = [24,27,30,31,33]
compagnie_faible = []
for i in range(100):
    compagnie_faible.append(random.choice(possibility_compagnie_faible))

print('compagnie_faible', compagnie_faible)

possibility_compagnie_forte = [34,37,38,41,45]
compagnie_forte = []
for i in range(100):
    compagnie_forte.append(random.choice(possibility_compagnie_forte))
print('compagnie_forte', compagnie_forte)


# compagnie_faible = [24,27,30,31,33] * 10
# print(compagnie_faible)

compagnie_faible [31, 24, 33, 31, 31, 33, 33, 31, 33, 27, 27, 33, 31, 31, 30, 30, 30, 33, 30, 30, 30, 30, 24, 30, 27, 30, 33, 24, 24, 24, 24, 31, 30, 27, 27, 30, 24, 31, 30, 33, 27, 24, 27, 27, 31, 33, 30, 24, 27, 24, 30, 33, 33, 33, 27, 24, 31, 30, 33, 33, 27, 30, 27, 24, 33, 30, 33, 24, 24, 27, 30, 33, 30, 24, 24, 27, 30, 31, 31, 24, 24, 24, 27, 30, 31, 24, 30, 30, 24, 27, 27, 30, 30, 24, 30, 27, 31, 24, 27, 24]
compagnie_forte [41, 45, 45, 38, 41, 34, 34, 45, 38, 41, 41, 45, 38, 38, 34, 37, 41, 37, 41, 45, 37, 41, 41, 45, 41, 34, 41, 34, 34, 37, 45, 34, 45, 41, 41, 41, 38, 38, 37, 37, 37, 41, 41, 34, 34, 41, 45, 45, 45, 45, 41, 45, 37, 45, 38, 41, 34, 41, 41, 37, 38, 41, 37, 41, 41, 37, 41, 34, 41, 34, 41, 34, 38, 41, 37, 41, 41, 45, 38, 37, 41, 38, 34, 37, 34, 38, 45, 41, 38, 37, 41, 38, 34, 41, 34, 38, 37, 45, 45, 41]


In [5]:
# Définir les étiquettes des données d'entraînement : 
# 0 = envoyer un troll
# 1 = envoyer deux trolls

etiquettes_zeros_like = np.zeros_like(compagnie_faible)
print(etiquettes_zeros_like)
etiquettes_one_like = np.ones_like(compagnie_forte)
print(etiquettes_one_like)
#? indice : zero_like()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [6]:
# Concaténer les données et les étiquettes
donnees_entree = np.concatenate((compagnie_faible, compagnie_forte), axis=0)
print(donnees_entree)

etiquettes = np.concatenate((etiquettes_zeros_like, etiquettes_one_like), axis=0)
print(etiquettes)

#? indice : np.concatenate()

[31 24 33 31 31 33 33 31 33 27 27 33 31 31 30 30 30 33 30 30 30 30 24 30
 27 30 33 24 24 24 24 31 30 27 27 30 24 31 30 33 27 24 27 27 31 33 30 24
 27 24 30 33 33 33 27 24 31 30 33 33 27 30 27 24 33 30 33 24 24 27 30 33
 30 24 24 27 30 31 31 24 24 24 27 30 31 24 30 30 24 27 27 30 30 24 30 27
 31 24 27 24 41 45 45 38 41 34 34 45 38 41 41 45 38 38 34 37 41 37 41 45
 37 41 41 45 41 34 41 34 34 37 45 34 45 41 41 41 38 38 37 37 37 41 41 34
 34 41 45 45 45 45 41 45 37 45 38 41 34 41 41 37 38 41 37 41 41 37 41 34
 41 34 41 34 38 41 37 41 41 45 38 37 41 38 34 37 34 38 45 41 38 37 41 38
 34 41 34 38 37 45 45 41]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 

In [7]:
# Mélanger les données 

In [8]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
print(donnees_entree)
etiquettes = etiquettes[indices_melanges]
print(etiquettes)

[24 30 33 41 41 24 38 41 24 45 41 31 33 41 45 38 45 33 45 38 27 30 41 31
 34 30 33 45 41 34 24 41 34 37 30 41 38 34 41 30 27 24 30 33 45 37 37 34
 45 24 30 38 24 27 27 33 31 41 41 34 45 30 38 24 30 34 30 38 33 30 37 24
 37 30 27 33 34 27 34 27 38 45 45 27 41 41 45 33 45 27 30 41 41 34 37 41
 30 45 34 37 31 30 38 41 33 34 37 30 30 31 31 24 30 41 41 31 34 31 45 24
 24 37 38 41 38 24 27 27 33 31 24 41 27 30 24 24 31 41 34 30 41 45 30 45
 41 30 34 41 30 27 24 37 37 41 41 33 33 31 41 41 37 38 24 45 41 27 34 45
 41 41 37 27 24 33 27 30 37 38 27 37 41 30 31 37 27 24 30 24 24 27 24 33
 33 38 31 31 38 34 33 24]
[0 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1
 1 1 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 0
 0 0 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0
 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1
 0 0 0 1 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0
 0 0 0 0 0 0 0 

In [9]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(1, input_dim=1, activation='sigmoid'))
## permet de former un modèle avec 1 couche (1 neurone), recevant une seule donnée (input_dim=1)
## la fonction d'activation du modèle est la fonction sigmoide

In [10]:
modele = Sequential()
modele.add(Dense(1, input_dim=1, activation='sigmoid'))

C:\Users\gaeta\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [11]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [12]:
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
# Entraîner le modèle
## ce sera à vous de rechercher comment fonctionne cette commande

In [14]:
modele.fit(donnees_entree, etiquettes, epochs=200, batch_size=1)

Epoch 1/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 692us/step - accuracy: 0.5263 - loss: 9.3635   
Epoch 2/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.5237 - loss: 6.8011 
Epoch 3/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.5014 - loss: 4.2653  
Epoch 4/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.5049 - loss: 1.6138
Epoch 5/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.4302 - loss: 0.7305
Epoch 6/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.4561 - loss: 0.7334 
Epoch 7/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.4863 - loss: 0.7255
Epoch 8/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step - accuracy: 0.5724 - loss: 0.6900
Epoch 9/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - accuracy: 0.5632 - loss: 0.7060
Epoch 10/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.4885 - loss: 0.7177 
Epoch 11/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.4847 - loss: 0.7181
Epoch 12/20

200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.9050 - loss: 0.4760
Epoch 132/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.8778 - loss: 0.4801
Epoch 133/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.9306 - loss: 0.4938
Epoch 134/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.8682 - loss: 0.4794
Epoch 135/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step - accuracy: 0.8851 - loss: 0.4986
Epoch 136/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.8847 - loss: 0.4922
Epoch 137/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.9170 - loss: 0.4965
Epoch 138/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.7828 - loss: 0.4917
Epoch 139/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.8813 - loss: 0.5036
Epoch 140/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.9247 - loss: 0.4792
Epoch 141/200
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.9245 - loss: 0.4730
Epoch 142/200

In [15]:
# Évaluer le modèle

In [16]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9100 - loss: 0.4027 
Perte : 0.4197976589202881, Précision : 0.9150000214576721


In [17]:
# Demander à afficher les prédictions associées à chaque compagnie
# Si la prédiction est > à 0.5, cela signifie que la compagnie est dangereuse
print(donnees_entree)
modele.predict(donnees_entree)

[24 30 33 41 41 24 38 41 24 45 41 31 33 41 45 38 45 33 45 38 27 30 41 31
 34 30 33 45 41 34 24 41 34 37 30 41 38 34 41 30 27 24 30 33 45 37 37 34
 45 24 30 38 24 27 27 33 31 41 41 34 45 30 38 24 30 34 30 38 33 30 37 24
 37 30 27 33 34 27 34 27 38 45 45 27 41 41 45 33 45 27 30 41 41 34 37 41
 30 45 34 37 31 30 38 41 33 34 37 30 30 31 31 24 30 41 41 31 34 31 45 24
 24 37 38 41 38 24 27 27 33 31 24 41 27 30 24 24 31 41 34 30 41 45 30 45
 41 30 34 41 30 27 24 37 37 41 41 33 33 31 41 41 37 38 24 45 41 27 34 45
 41 41 37 27 24 33 27 30 37 38 27 37 41 30 31 37 27 24 30 24 24 27 24 33
 33 38 31 31 38 34 33 24]
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[0.22943188],
       [0.41787452],
       [0.5270994 ],
       [0.7827663 ],
       [0.7827663 ],
       [0.22943188],
       [0.69885504],
       [0.7827663 ],
       [0.22943188],
       [0.8662891 ],
       [0.7827663 ],
       [0.45392233],
       [0.5270994 ],
       [0.7827663 ],
       [0.8662891 ],
       [0.69885504],
       [0.8662891 ],
       [0.5270994 ],
       [0.8662891 ],
       [0.69885504],
       [0.31615186],
       [0.41787452],
       [0.7827663 ],
       [0.45392233],
       [0.5634495 ],
       [0.41787452],
       [0.5270994 ],
       [0.8662891 ],
       [0.7827663 ],
       [0.5634495 ],
       [0.22943188],
       [0.7827663 ],
       [0.5634495 ],
       [0.6671188 ],
       [0.41787452],
       [0.7827663 ],
       [0.69885504],
       [0.5634495 ],
       [0.7827663 ],
       [0.41787452],
       [0.31615186],
       [0.22943188],
       [0.41787452],
       [0.5270994 ],
       [0.8662891 ],
       [0.6671188 ],
       [0.6671188 ],
       [0.563

In [18]:
# Pouvez-vous en déduire l'équation utilisée dans ce modèle,
# pour déterminer la valeur du "x" qui est transmis à la 
# fonction d'activation sigmoide ? 
# non
# force compagnie:
#38
# poids:
# -0.00418886
# 0.45334148
# resultat
0.5730154

0.5730154

In [19]:
# Afficher, pour les 10 premières compagnies qui se présentent au donjon :
    # La puissance des compagnies
    # les étiquettes associées (0 ou 1)
    # les prédictions, 
    # et la décision à prendre, en chaine de caractère

In [20]:
predictions = modele.predict(donnees_entree)
resultat = []
for i in range(10) :
    if predictions[i] < 0.5 :
        resultat.append('1 troll')
    else :
        resultat.append('2 troll')

print(predictions[0:10])
print(etiquettes[0:10])
print(resultat)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
[[0.22943188]
 [0.41787452]
 [0.5270994 ]
 [0.7827663 ]
 [0.7827663 ]
 [0.22943188]
 [0.69885504]
 [0.7827663 ]
 [0.22943188]
 [0.8662891 ]]
[0 0 0 1 1 0 1 1 0 1]
['1 troll', '1 troll', '2 troll', '2 troll', '2 troll', '1 troll', '2 troll', '2 troll', '1 troll', '2 troll']


In [21]:
# Afficher les poids du modèle

In [22]:
multiple_poids = modele.weights
for poids in multiple_poids:
    print(poids.value)

# weights = [np.array(weight) for weight in modele.weights]

# # Afficher les poids
# for i, weight_array in enumerate(weights):
#     print(f"Poids {i + 1}:")
#     print(weight_array)

<tf.Variable 'sequential/dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.14666954]], dtype=float32)>
<tf.Variable 'sequential/dense/bias:0' shape=(1,) dtype=float32, numpy=array([-4.7315907], dtype=float32)>


In [23]:
# Afficher les informations résumées relatives au modèle

In [24]:
modele.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8 (36.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6 (28.00 B)