In [64]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import pandas as pd
import itertools

In [65]:
# # Créer toutes les positiblités de 8 colonnes binaire
# columns = ['Colonne_{}'.format(i+1) for i in range(8)]
# df = pd.DataFrame(columns=columns)

# # Générer toutes les combinaisons possibles de valeurs binaires
# combinaisons_binaires = list(itertools.product([0, 1], repeat=8))

# # Remplir le DataFrame avec les combinaisons binaires
# for comb in combinaisons_binaires:
#     df_comb = pd.DataFrame(data = [comb], columns=columns)
#     df = pd.concat([df, df_comb], ignore_index=True)

# print(df)

In [66]:
requin = [[1,1,1,1,1,0,0,0],[0,0,1,1,1,0,0,0],[0,1,1,0,1,0,0,0],[1,1,0,0,1,0,0,0],[1,0,0,0,1,0,0,0],
          [0,1,1,1,0,0,0,0],[1,0,0,1,0,0,0,0],[0,1,0,1,0,0,0,0]]
baleine = [[0,0,0,1,1,1,0,1],[0,0,1,1,0,1,0,1],[0,0,0,0,1,0,1,1],[0,0,0,0,1,1,0,0],[0,0,0,1,0,0,0,1],
           [0,0,0,1,1,0,1,0],[0,0,0,1,0,0,1,0],[0,0,0,0,1,0,0,1]]


valeurs_entree_requin = []
valeurs_entree_baleine = []

for i in range(25) :
    for val in range(8) :
        valeurs_entree_requin.append(requin[val])
        valeurs_entree_baleine.append(baleine[val])

# Étiquettes correspondantes (0 pour la catégorie 0, 1 pour la catégorie 1)
etiquettes_cat_requin = np.zeros(len(valeurs_entree_requin), dtype = int)
etiquettes_cat_baleine = np.ones(len(valeurs_entree_baleine), dtype = int)

# Concaténer les données et les étiquettes
donnees_entree = np.concatenate([valeurs_entree_requin, valeurs_entree_baleine])
print(donnees_entree)
etiquettes = np.concatenate([etiquettes_cat_requin, etiquettes_cat_baleine])
print(etiquettes)

# Mélanger les données
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
print(donnees_entree)
etiquettes = etiquettes[indices_melanges]
print(etiquettes)

[[1 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[0 0 0 ... 0 1 1]
 [0 0 0 ... 0 1 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 

In [67]:
# Créer le modèle
modele = Sequential()
modele.add(Dense(1, input_dim=8, activation='sigmoid'))

# Compiler le modèle
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entraîner le modèle
modele.fit(donnees_entree, etiquettes, epochs=100, batch_size=1)

Epoch 1/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 589us/step - accuracy: 0.6888 - loss: 0.6717
Epoch 2/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step - accuracy: 0.7606 - loss: 0.5670
Epoch 3/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.8082 - loss: 0.4763
Epoch 4/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.9114 - loss: 0.4078
Epoch 5/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - accuracy: 1.0000 - loss: 0.3422
Epoch 6/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 1.0000 - loss: 0.3011
Epoch 7/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 1.0000 - loss: 0.2632
Epoch 8/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 1.0000 - loss: 0.2216
Epoch 9/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step - accuracy: 1.0000 - loss: 0.1949
Epoch 10/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 1.0000 - loss: 0.1737
Epoch 11/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 1.0000 - loss: 0.1582
Epoch 12/100
400/40

400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 1.0000 - loss: 7.4199e-04
Epoch 67/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 1.0000 - loss: 6.9170e-04
Epoch 68/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 1.0000 - loss: 5.2169e-04
Epoch 69/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 1.0000 - loss: 5.5531e-04
Epoch 70/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step - accuracy: 1.0000 - loss: 4.9695e-04
Epoch 71/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 1.0000 - loss: 4.3985e-04
Epoch 72/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - accuracy: 1.0000 - loss: 4.1701e-04
Epoch 73/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 1.0000 - loss: 3.5025e-04
Epoch 74/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - accuracy: 1.0000 - loss: 3.4686e-04
Epoch 75/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 1.0000 - loss: 2.9979e-04
Epoch 76/100
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 1.000

In [68]:
# Évaluer le modèle
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")


data_to_evaluate = np.array([[0,0,1,1,1,0,0,0],[1,1,1,1,1,1,0,0],[1,1,1,0,1,0,0,0],[0,0,0,1,1,1,1,0],[1,0,0,0,1,1,0,1],
          [0,1,1,1,1,0,0,0],[0,0,0,1,0,0,0,0],[1,1,0,1,0,0,0,0]])
0
# Prédictions
predictions = modele.predict(data_to_evaluate)
print("Prédictions:")
print(predictions)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 1.0000 - loss: 3.3242e-05
Perte : 3.1144623790169135e-05, Précision : 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Prédictions:
[[1.4469022e-04]
 [6.0398038e-09]
 [3.7591458e-12]
 [1.0000000e+00]
 [9.9996769e-01]
 [1.3551432e-08]
 [2.4694803e-01]
 [1.4251484e-09]]
