In [1]:
# Importer les bibliothèques nécessaires au programme

In [2]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les vecteurs de taille 8 ou chaque élément est une caractéristique d'un 
# animal (requin ou baleine)

## shéma des données : 
#[nageoire caudale asymetrique, 
# peau lisse, 
# fentes brachiales, 
# grande taille, 
# océan,
# sillons ventraux,
# évents en V sur le dessus de la tête
# nageoire caudale symétrique]

# les 3 premières caractéristiques sont celles spécifiques au requin 
# les 3 dernières caractéristiques sont celles spécifiques à la baleine 
# les 2 caractéristiques au centre sont communes à la baleine et au requin 

## shéma du perceptron : 
# caractéristiques----poids des caractéristiques----neurones Relu---- neurones softmax ------>prediction


In [4]:
requin_parfait = [1,1,1,1,1,0,0,0]
baleine_parfaite = [0,0,0,1,1,1,1,1]

requin_imparfait_1 = [0,1,1,1,1,0,0,0]
requin_imparfait_2 = [1,0,1,1,1,0,0,0]
requin_imparfait_3 = [0,1,1,0,1,0,0,0]
requin_imparfait_4 = [1,0,1,0,1,0,0,0]
requin_imparfait_5 = [0,1,1,1,0,0,0,0]
requin_imparfait_6 = [1,0,1,1,0,0,0,0]

baleine_imparfait_1 = [0,0,0,1,1,1,0,1]
baleine_imparfait_2 = [0,0,0,1,1,0,1,1]
baleine_imparfait_3 = [0,0,0,0,1,1,0,1]
baleine_imparfait_4 = [0,0,0,0,1,0,1,1]
baleine_imparfait_5 = [0,0,0,1,0,1,0,1]
baleine_imparfait_6 = [0,0,0,1,0,0,1,1]

requins = [requin_parfait, requin_imparfait_1, requin_imparfait_2, requin_imparfait_3, requin_imparfait_4, requin_imparfait_5, requin_imparfait_6]
baleines = [baleine_parfaite, baleine_imparfait_1, baleine_imparfait_2, baleine_imparfait_3, baleine_imparfait_4, baleine_imparfait_5, baleine_imparfait_6] 

In [5]:
# Creer un plus grand jeu de données pour améliorer l'apprentissage du perceptron

In [6]:
animaux_cat0 = []
animaux_cat1 = []

for animaux in range(7) :
    for id_animal in range(7) :  
        animaux_cat0.append(requins[id_animal])
        animaux_cat1.append(baleines[id_animal])    

In [7]:
# Définir les étiquettes des données d'entraînement : 
# 0 = l'animal est un requin
# 1 = l'animal est une baleine

In [8]:
etiquettes_cat0 = []
etiquettes_cat1 = []

for animal in range(len(animaux_cat0)) :
    etiquettes_cat0.append([1,0])
    etiquettes_cat1.append([0,1])

In [9]:
# Concaténer les données et les étiquettes 

In [10]:
donnees_entree = np.concatenate([animaux_cat0, animaux_cat1])
etiquettes = np.concatenate([etiquettes_cat0, etiquettes_cat1])

In [11]:
# Mélanger les données 

In [12]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
etiquettes = etiquettes[indices_melanges]

In [13]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(10, input_dim=8, activation='relu'))
## modele.add(Dense(2, activation='softmax')
## permet de former un modèle avec 1 couche cachée (10 neurones), recevant 8 données (input_dim=8)
## et une couche de sortie (2 neurones)
## la fonction d'activation du modèle est la fonction relu (couche cachée) et la fonction softmax (couche de sortie)

In [14]:
modele = Sequential()
modele.add(Dense(80, input_dim=8, activation='relu'))
modele.add(Dense(2, activation='softmax'))

C:\Users\gaeta\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [16]:
modele.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [17]:
# Entraîner le modèle
## ce sera à vous de rechercher comment fonctionne cette commande

In [18]:
modele.fit(donnees_entree, etiquettes, epochs=20, batch_size=1)

Epoch 1/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 820us/step - accuracy: 0.6347 - loss: 0.6119    
Epoch 2/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step - accuracy: 1.0000 - loss: 0.1834
Epoch 3/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 1.0000 - loss: 0.0527
Epoch 4/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - accuracy: 1.0000 - loss: 0.0221
Epoch 5/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 1.0000 - loss: 0.0114
Epoch 6/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 1.0000 - loss: 0.0056
Epoch 7/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 1.0000 - loss: 0.0039
Epoch 8/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 1.0000 - loss: 0.0026
Epoch 9/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - accuracy: 1.0000 - loss: 0.0021 
Epoch 10/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 1.0000 - loss: 0.0016
Epoch 11/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 1.0000 - loss: 0.0012 
Epoch 12/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 650u

In [19]:
# Évaluer le modèle

In [20]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.5537e-04 
Perte : 0.0002708885003812611, Précision : 1.0


In [21]:
# Demander à afficher les prédictions associées à chaque animal

In [22]:
predictions_requin = modele.predict(np.array(requins))
predictions_baleine = modele.predict(np.array(baleines))
print("Prédictions baleine:")
print(predictions_baleine)
print("Prédictions requin:")
print(predictions_requin)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Prédictions baleine:
[[4.7314215e-06 9.9999523e-01]
 [1.2999585e-04 9.9986994e-01]
 [5.8383113e-05 9.9994159e-01]
 [2.7678811e-04 9.9972314e-01]
 [1.3584267e-04 9.9986410e-01]
 [2.5663304e-04 9.9974340e-01]
 [1.2904881e-04 9.9987090e-01]]
Prédictions requin:
[[9.9997604e-01 2.3922552e-05]
 [9.9976760e-01 2.3237754e-04]
 [9.9978942e-01 2.1057844e-04]
 [9.9947709e-01 5.2288652e-04]
 [9.9945062e-01 5.4936338e-04]
 [9.9944681e-01 5.5321504e-04]
 [9.9958760e-01 4.1236266e-04]]


In [23]:
# Afficher les poids du modèle

In [25]:
modele.get_weights()

[array([[-1.59892216e-01, -1.37087116e-02, -2.98328996e-01,
          1.58514708e-01, -2.38718495e-01, -1.44414514e-01,
         -1.85489103e-01,  2.21234247e-01,  1.33716926e-01,
         -2.54244834e-01, -2.45268524e-01,  1.25118783e-02,
         -1.54014081e-01, -6.06816746e-02,  1.44035788e-02,
          1.60803199e-02,  1.31245106e-01,  9.70550105e-02,
          1.65897891e-01,  7.06005543e-02, -9.04371515e-02,
          3.94961029e-01, -1.54874355e-01, -1.61296502e-01,
         -2.64043927e-01,  3.28810930e-01,  9.78288800e-02,
          2.74435878e-02, -1.63460448e-01, -2.04153553e-01,
          1.92072630e-01, -2.53577709e-01, -2.17200473e-01,
          7.99890161e-02, -2.82846451e-01, -2.45195348e-02,
          3.17097872e-01, -4.80296910e-02, -1.89159103e-02,
         -7.07072392e-02,  1.86276078e-01, -3.79575640e-02,
         -5.15030585e-02, -2.13438526e-01, -1.52023688e-01,
          4.33936082e-02, -8.72838423e-02, -1.43798083e-01,
         -2.44395524e-01,  1.21731676e-0

In [26]:
# Afficher les informations résumées relatives au modèle

In [27]:
modele.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │             720 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │             162 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,648 (10.35 KB)

 Trainable params: 882 (3.45 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,766 (6.90 KB)

In [28]:
print(donnees_entree[0])

[1 1 1 1 1 0 0 0]


In [40]:
X = np.array([[0, 0, 0, 0, 0, 0, 0, 1]])
predictions = modele.predict(X)
print("Prédictions:")
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Prédictions:
[[0.00693158 0.99306846]]


In [30]:
result = 2.4739696e-10
print(result)

2.4739696e-10
