In [1]:
# Importer les bibliothèques nécessaires au programme

In [2]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les vecteurs de taille 8 ou chaque élément est une caractéristique d'un 
# animal (requin ou baleine)

## shéma des données : 
#[nageoire caudale asymetrique, 
# peau lisse, 
# fentes brachiales, 
# grande taille, 
# océan,
# sillons ventraux,
# évents en V sur le dessus de la tête
# nageoire caudale symétrique]

# les 3 premières caractéristiques sont celles spécifiques au requin 
# les 3 dernières caractéristiques sont celles spécifiques à la baleine 
# les 2 caractéristiques au centre sont communes à la baleine et au requin 

## shéma du perceptron : 
# caractéristiques ------poids des caractéristiques-----neurones------>prediction


In [4]:
requin_parfait = [1,1,1,1,1,0,0,0]
baleine_parfaite = [0,0,0,1,1,1,1,1]

requin_imparfait_1 = [0,1,1,1,1,0,0,0]
requin_imparfait_2 = [1,0,1,1,1,0,0,0]
requin_imparfait_3 = [0,1,1,0,1,0,0,0]
requin_imparfait_4 = [1,0,1,0,1,0,0,0]
requin_imparfait_5 = [0,1,1,1,0,0,0,0]
requin_imparfait_6 = [1,0,1,1,0,0,0,0]

baleine_imparfait_1 = [0,0,0,1,1,1,0,1]
baleine_imparfait_2 = [0,0,0,1,1,0,1,1]
baleine_imparfait_3 = [0,0,0,0,1,1,0,1]
baleine_imparfait_4 = [0,0,0,0,1,0,1,1]
baleine_imparfait_5 = [0,0,0,1,0,1,0,1]
baleine_imparfait_6 = [0,0,0,1,0,0,1,1]

requins = [requin_parfait, requin_imparfait_1, requin_imparfait_2, requin_imparfait_3, requin_imparfait_4, requin_imparfait_5, requin_imparfait_6]
baleines = [baleine_parfaite, baleine_imparfait_1, baleine_imparfait_2, baleine_imparfait_3, baleine_imparfait_4, baleine_imparfait_5, baleine_imparfait_6] 

In [5]:
# Creer un plus grand jeu de données pour améliorer l'apprentissage du perceptron

In [6]:
animaux_cat0 = []
animaux_cat1 = []

for animaux in range(7) :
    for id_animal in range(7) :  
        animaux_cat0.append(requins[id_animal])
        animaux_cat1.append(baleines[id_animal])    

In [7]:
# Définir les étiquettes des données d'entraînement : 
# [1,0] = l'animal est un requin
# [0,1] = l'animal est une baleine

In [8]:
etiquettes_cat0 = []
etiquettes_cat1 = []

for animal in range(len(animaux_cat0)) :
    etiquettes_cat0.append([1,0])
    etiquettes_cat1.append([0,1])

In [9]:
# Concaténer les données et les étiquettes 

In [10]:
donnees_entree = np.concatenate([animaux_cat0, animaux_cat1])
etiquettes = np.concatenate([etiquettes_cat0, etiquettes_cat1])

In [11]:
# Mélanger les données 

In [12]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
etiquettes = etiquettes[indices_melanges]

In [13]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(2, input_dim=8, activation='sigmoid'))
## permet de former un modèle avec 1 couche (2 neurones), chaque neurone recevant 8 données (input_dim=8)
## la fonction d'activation du modèle est la fonction sigmoid

In [14]:
modele = Sequential()
modele.add(Dense(2, input_dim=8, activation='sigmoid'))

C:\Users\gaeta\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'binary_crossentropy' car nous voulons distinguer 2 groupes
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [16]:
modele.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
# Entraîner le modèle

In [18]:
modele.fit(donnees_entree, etiquettes, epochs=10, batch_size=1)

Epoch 1/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - accuracy: 0.6283 - loss: 0.6465
Epoch 2/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.8185 - loss: 0.5903
Epoch 3/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.8602 - loss: 0.5451
Epoch 4/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.9673 - loss: 0.4847
Epoch 5/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step - accuracy: 1.0000 - loss: 0.4467
Epoch 6/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - accuracy: 1.0000 - loss: 0.4097
Epoch 7/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step - accuracy: 1.0000 - loss: 0.3717
Epoch 8/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 1.0000 - loss: 0.3430
Epoch 9/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 1.0000 - loss: 0.3150
Epoch 10/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 1.0000 - loss: 0.2939


In [19]:
# Évaluer le modèle

In [20]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2801 
Perte : 0.2748253047466278, Précision : 1.0


In [21]:
# Demander à afficher les prédictions associées à chaque animal

In [24]:
predictions_requin = modele.predict(np.array(requins))
predictions_baleine = modele.predict(np.array(baleines))
print("Prédictions baleine:")
print(predictions_baleine)
print("Prédictions requin:")
print(predictions_requin)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Prédictions baleine:
[[0.22630124 0.83224714]
 [0.21094152 0.78958917]
 [0.25235704 0.8170073 ]
 [0.22542498 0.78684753]
 [0.2687157  0.814539  ]
 [0.21792127 0.7291298 ]
 [0.26025513 0.76205206]]
Prédictions requin:
[[0.8016394  0.18138681]
 [0.7358234  0.23761795]
 [0.68394035 0.3211314 ]
 [0.7519994  0.23465554]
 [0.7020067  0.3175615 ]
 [0.74379927 0.18272072]
 [0.6928288  0.25335172]]


In [25]:
# Afficher les poids du modèle

In [40]:
#modele.weights
modele.get_weights()

[array([[ 0.3722001 , -0.3411964 ],
        [ 0.6246325 , -0.75840276],
        [ 0.45755717, -0.6618089 ],
        [-0.08493244,  0.01642379],
        [-0.04143799,  0.3322385 ],
        [-0.14323467,  0.10543586],
        [ 0.08994404,  0.2791868 ],
        [-1.1182072 ,  0.96258664]], dtype=float32),
 array([ 0.06855279, -0.09423415], dtype=float32)]

In [28]:
# Afficher les informations résumées relatives au modèle

In [42]:
modele.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │              18 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 56 (228.00 B)

 Trainable params: 18 (72.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 38 (156.00 B)

In [30]:
print(donnees_entree[0])

[1 0 1 0 1 0 0 0]


In [36]:
X = np.array([[1, 0, 1, 0, 0, 0, 0, 0]])
predictions = modele.predict(X)
print("Prédictions:")
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Prédictions:
[[0.7106021  0.25025755]]


In [32]:
result = round(2.4739696e-10,3)
print(result)

0.0
