In [1]:
# Importer les bibliothèques nécessaires au programme

In [2]:
import random
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Définir les données servant à entraîner l'IA 
# c'est à dire les vecteurs de taille 8 ou chaque élément est une caractéristique d'un 
# animal (requin ou baleine)

## shéma des données : 
#[nageoire caudale asymetrique, 
# peau lisse, 
# fentes brachiales, 
# grande taille, 
# océan,
# sillons ventraux,
# évents en V sur le dessus de la tête
# nageoire caudale symétrique]

# les 3 premières caractéristiques sont celles spécifiques au requin 
# les 3 dernières caractéristiques sont celles spécifiques à la baleine 
# les 2 caractéristiques au centre sont communes à la baleine et au requin 

## shéma du perceptron : 
# caractéristiques ------poids des caractéristiques-----neurones------>prediction


In [4]:
requin_parfait = [1,1,1,1,1,0,0,0]
baleine_parfaite = [0,0,0,1,1,1,1,1]

requin_imparfait_1 = [0,1,1,1,1,0,0,0]
requin_imparfait_2 = [1,0,1,1,1,0,0,0]
requin_imparfait_3 = [0,1,1,0,1,0,0,0]
requin_imparfait_4 = [1,0,1,0,1,0,0,0]
requin_imparfait_5 = [0,1,1,1,0,0,0,0]
requin_imparfait_6 = [1,0,1,1,0,0,0,0]

baleine_imparfait_1 = [0,0,0,1,1,1,0,1]
baleine_imparfait_2 = [0,0,0,1,1,0,1,1]
baleine_imparfait_3 = [0,0,0,0,1,1,0,1]
baleine_imparfait_4 = [0,0,0,0,1,0,1,1]
baleine_imparfait_5 = [0,0,0,1,0,1,0,1]
baleine_imparfait_6 = [0,0,0,1,0,0,1,1]

requins = [requin_parfait, requin_imparfait_1, requin_imparfait_2, requin_imparfait_3, requin_imparfait_4, requin_imparfait_5, requin_imparfait_6]
baleines = [baleine_parfaite, baleine_imparfait_1, baleine_imparfait_2, baleine_imparfait_3, baleine_imparfait_4, baleine_imparfait_5, baleine_imparfait_6] 

In [5]:
# Creer un plus grand jeu de données pour améliorer l'apprentissage du perceptron

In [6]:
animaux_cat0 = []
animaux_cat1 = []

for animaux in range(7) :
    for id_animal in range(7) :  
        animaux_cat0.append(requins[id_animal])
        animaux_cat1.append(baleines[id_animal])    

In [7]:
# Définir les étiquettes des données d'entraînement : 
# [1,0] = l'animal est un requin
# [0,1] = l'animal est une baleine

In [8]:
etiquettes_cat0 = []
etiquettes_cat1 = []

for animal in range(len(animaux_cat0)) :
    etiquettes_cat0.append([1,0])
    etiquettes_cat1.append([0,1])

In [9]:
# Concaténer les données et les étiquettes 

In [10]:
donnees_entree = np.concatenate([animaux_cat0, animaux_cat1])
etiquettes = np.concatenate([etiquettes_cat0, etiquettes_cat1])

In [11]:
# Mélanger les données 

In [12]:
indices_melanges = np.random.permutation(len(donnees_entree))
donnees_entree = donnees_entree[indices_melanges]
etiquettes = etiquettes[indices_melanges]

In [13]:
# Créer le modèle

## Sequential() est une architecture de perceptron bien adaptée à la classification binaire
## modele.add(Dense(2, input_dim=8, activation='softmax'))
## permet de former un modèle avec 1 couche (2 neurone), chaque neurone recevant 8 données (input_dim=8)
## la fonction d'activation du modèle est la fonction softmax, qui permet d'exprimer la probabilité d'appartenance d'un exemple à une catégorie

In [14]:
modele = Sequential()
modele.add(Dense(2, input_dim=8, activation='softmax'))

C:\Users\gaeta\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
# Compiler le modèle
## optimizer désigne l'algorithme en charge de la modification des poids 
## loss mesure la distance entre la prediction du neurone et le résultat souhaité
## ici nous utilisons l'algorithme 'categorical_crossentropy' car nous utilisons softmax
## metrics indique, sur une échelle de 0 à 1, le ratio de prédictions correctes pour un cycle d'entraînement

In [16]:
modele.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [17]:
# Entraîner le modèle

In [18]:
modele.fit(donnees_entree, etiquettes, epochs=10, batch_size=1)

Epoch 1/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 857us/step - accuracy: 0.1767 - loss: 1.0592   
Epoch 2/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.3242 - loss: 0.8190   
Epoch 3/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.4740 - loss: 0.6957
Epoch 4/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.5541 - loss: 0.5549   
Epoch 5/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.7117 - loss: 0.4865 
Epoch 6/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.9112 - loss: 0.4334
Epoch 7/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 1.0000 - loss: 0.3551
Epoch 8/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - accuracy: 1.0000 - loss: 0.3258
Epoch 9/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 1.0000 - loss: 0.2654
Epoch 10/10
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 1.0000 - loss: 0.2472


In [19]:
# Évaluer le modèle

In [20]:
perte, precision = modele.evaluate(donnees_entree, etiquettes)
print(f"Perte : {perte}, Précision : {precision}")

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.2303  
Perte : 0.22714410722255707, Précision : 1.0


In [21]:
# Demander à afficher les prédictions associées à chaque compagnie

In [23]:
predictions_requin = modele.predict(np.array(requins))
predictions_baleine = modele.predict(np.array(baleines))
print("Prédictions baleine:")
print(predictions_baleine)
print("Prédictions requin:")
print(predictions_requin)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Prédictions baleine:
[[0.06906664 0.93093336]
 [0.32101747 0.67898256]
 [0.08412909 0.9158709 ]
 [0.2904978  0.7095022 ]
 [0.07368664 0.9263134 ]
 [0.31134656 0.6886534 ]
 [0.08074595 0.91925406]]
Prédictions requin:
[[0.86634564 0.1336544 ]
 [0.86683416 0.13316587]
 [0.7117954  0.2882046 ]
 [0.8493337  0.15066631]
 [0.68140846 0.3185915 ]
 [0.8615854  0.13841462]
 [0.7025329  0.29746714]]


In [24]:
# Afficher les poids du modèle

In [27]:
modele.get_weights()

[array([[ 0.00476552,  0.00899106],
        [-0.10012205, -1.0650289 ],
        [ 0.490688  ,  0.02315776],
        [ 0.43562368,  0.291756  ],
        [-0.32068157, -0.3654131 ],
        [ 0.20013885,  0.41373113],
        [-0.69743234,  1.1545835 ],
        [-0.9533009 ,  0.02302174]], dtype=float32),
 array([ 0.12610795, -0.12610793], dtype=float32)]

In [28]:
# Afficher les informations résumées relatives au modèle

In [29]:
modele.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │              18 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 56 (228.00 B)

 Trainable params: 18 (72.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 38 (156.00 B)

In [30]:
print(donnees_entree[0])

[1 1 1 1 1 0 0 0]


In [31]:
X = np.array([[1, 1, 1, 0, 0, 1, 1, 1]])
predictions = modele.predict(X)
print("Prédictions:")
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Prédictions:
[[0.2039961 0.7960039]]


In [32]:
result = round(2.4739696e-10,3)
print(result)

0.0
